#!/bin/bash

nvidia-docker run -d -it --init --network host --name ml-machine -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 -p 0.0.0.0:8888:8888 -p 0.0.0.0:5678:5678 --restart unless-stopped -v ~/workspace:/workspace pvasek/ml-machine